[SyntaxError]: Identifier has already been declared. (1,36)
1|let foo; try {} catch (foo) {} let foo;
 |                                  ^
